apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kms-generic-helm-charts.fullname" . }}-config
  labels:
    {{- include "notebook-search-app.labels" . | nindent 4 }}

data:
  ELASTICSEARCH_URL : {{ .Values.elasticsearch.kms_generic.elasticsearch_url | default "http://"{{ .Release.Name }}-elasticsearch:"9200" }} }}
  ELASTICSEARCH_USERNAME : {{ .Values.elasticsearch.elasticUsername | default "elastic" | quote }} }}
  ELASTICSEARCH_PASSWORD : {{ .Values.elasticsearch.elasticPassword }}
  ACCESS_TOKEN_Github: ""
  ACCESS_TOKEN_Gitlab: ""
  GITHUB_QUERY_URL: {{ .Values.elasticsearch.kms_generic.github_query_url | default "https://api.github.com/search/code?l=Jupyter+Notebook&q=ipynb+in:path+extension:ipynb" }}
  KMS_ADMIN_USERNAME:  {{ .Values.elasticsearch.kms_generic.kms_admin }}
  KMS_ADMIN_PASSWORD:  {{ .Values.elasticsearch.kms_generic.kms_password }}
  POSTGRES_HOSTNAME : {{ .Release.Name }}-postgresql
  POSTGRES_PORT : "5432"
  POSTGRES_USER : {{ .Values.postgresql.auth.username }}
  POSTGRES_DB : {{ .Values.postgresql.auth.database }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password }}
