apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kms-generic-helm-charts.fullname" . }}-config
  labels:
    {{- include "kms-generic-helm-charts.labels" . | nindent 4 }}

data:
{{- if .Values.kms_generic.elasticsearch.url }}
  ELASTICSEARCH_URL : {{ .Values.kms_generic.elasticsearch.url }}
{{- else }}
  ELASTICSEARCH_URL : "http://{{ .Release.Name }}-elasticsearch:9200"
{{- end }}
  ELASTICSEARCH_USERNAME : {{ .Values.elasticsearch.elasticUsername | default "elastic" | quote }}
  ELASTICSEARCH_PASSWORD : {{ .Values.elasticsearch.elasticPassword }}
  ACCESS_TOKEN_Github: ""
  ACCESS_TOKEN_Gitlab: ""
  GITHUB_QUERY_URL: {{ .Values.kms_generic.github_query_url | default "https://api.github.com/search/code?l=Jupyter+Notebook&q=ipynb+in:path+extension:ipynb" }}
  KMS_ADMIN_USERNAME:  {{ .Values.kms_generic.kms_admin }}
  KMS_ADMIN_PASSWORD:  {{ .Values.kms_generic.kms_password }}
  POSTGRES_HOSTNAME : {{ .Release.Name }}-postgresql
  POSTGRES_PORT : {{ .Values.postgresql.containerPorts.postgresql | default "5432" | quote }}
  POSTGRES_USER : {{ .Values.postgresql.auth.username }}
  POSTGRES_DB : {{ .Values.postgresql.auth.database }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password }}
