apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kms-generic-helm-charts.fullname" . }}
  labels:
    {{- include "kms-generic-helm-charts.labels" . | nindent 4 }}
spec:
  {{- if not .Values.kms_generic.autoscaling.enabled }}
  replicas: {{ .Values.kms_generic.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kms-generic-helm-charts.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.kms_generic.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kms-generic-helm-charts.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.kms_generic.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kms-generic-helm-charts.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.kms_generic.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.kms_generic.securityContext | nindent 12 }}
          image: "{{ .Values.kms_generic.image.repository }}:{{ .Values.kms_generic.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.kms_generic.image.pullPolicy }}
          env:
            - name: ELASTICSEARCH_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "kms-generic-helm-charts.fullname" . }}-config
                  key: ELASTICSEARCH_URL
            - name: GITHUB_API_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: {{ include "kms-generic-helm-charts.fullname" . }}-config
                  key: GITHUB_API_TOKEN
            - name: ACCESS_TOKEN_Gitlab
              valueFrom:
                configMapKeyRef:
                  name: {{ include "kms-generic-helm-charts.fullname" . }}-config
                  key: ACCESS_TOKEN_Gitlab
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: {{ include "kms-generic-helm-charts.fullname" . }}-config
                  key: ELASTICSEARCH_PASSWORD
            - name: ELASTICSEARCH_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "kms-generic-helm-charts.fullname" . }}-config
                  key: ELASTICSEARCH_USERNAME
            - name: GITHUB_QUERY_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "kms-generic-helm-charts.fullname" . }}-config
                  key: GITHUB_QUERY_URL
            - name: KMS_ADMIN_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "kms-generic-helm-charts.fullname" . }}-config
                  key: KMS_ADMIN_USERNAME
            - name: KMS_ADMIN_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: {{ include "kms-generic-helm-charts.fullname" . }}-config
                  key: KMS_ADMIN_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ include "kms-generic-helm-charts.fullname" . }}-config
                  key: POSTGRES_DB
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: {{ include "kms-generic-helm-charts.fullname" . }}-config
                  key: POSTGRES_PASSWORD
            - name: BASE_PATH
              valueFrom:
                configMapKeyRef:
                  name: {{ include "kms-generic-helm-charts.fullname" . }}-config
                  key: BASE_PATH
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 20
            httpGet:
              path: /{{ .Values.kms_generic.base_path | default "search" }}
              port: http
          readinessProbe:
            initialDelaySeconds: 20
            httpGet:
              path: /{{ .Values.kms_generic.base_path | default "search" }}
              port: http
          resources:
            {{- toYaml .Values.kms_generic.resources | nindent 12 }}

        - name: {{ .Chart.Name }}-indexer
          securityContext:
            {{- toYaml .Values.indexer.securityContext | nindent 12 }}
          image: "{{ .Values.indexer.image.repository }}:{{ .Values.indexer.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.indexer.image.pullPolicy }}
          env:
            - name: ELASTICSEARCH_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "kms-generic-helm-charts.fullname" . }}-config
                  key: ELASTICSEARCH_URL
            - name: ELASTICSEARCH_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "kms-generic-helm-charts.fullname" . }}-config
                  key: ELASTICSEARCH_USERNAME
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: {{ include "kms-generic-helm-charts.fullname" . }}-config
                  key: ELASTICSEARCH_PASSWORD
            - name: KAGGLE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "kms-generic-helm-charts.fullname" . }}-config
                  key: KAGGLE_USERNAME
            - name: KAGGLE_KEY
              valueFrom:
                configMapKeyRef:
                  name: {{ include "kms-generic-helm-charts.fullname" . }}-config
                  key: KAGGLE_KEY
            - name: GITHUB_API_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: {{ include "kms-generic-helm-charts.fullname" . }}-config
                  key: GITHUB_API_TOKEN

            - name: DATA_DIR
              value: "/app/data"

          volumeMounts:
          - name: indexer-data-storage
            mountPath: /app/data
          resources:
            {{- toYaml .Values.indexer.resources | nindent 12 }}

      volumes:
        - name: indexer-data-storage
        {{- if .Values.indexer.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "indexer.pvc" . }}
        {{- else }}
          emptyDir: {}
        {{ end }}

      {{- with .Values.kms_generic.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kms_generic.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kms_generic.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
