global:
  postgresqlEnabled: false
  elasticsearchEnabled: true

kms_generic:
  replicaCount: 1
  autoscaling:
    enabled: false
  image:
    pullPolicy: Always
  base_path: kms
  ingress:
    enabled: true
    className: "nginx"
    annotations:
        nginx.ingress.kubernetes.io/add-base-url: "true"
    hosts:
      - host: localhost
        paths:
          - path: /kms(/|$)(.*)
            pathType: ImplementationSpecific
    tls:
      - secretName: localhost
        hosts:
          - localhost
