name: Deploy KMS

on:
  workflow_dispatch:

permissions: 
  actions: read
  id-token: write 
  contents: read

jobs:
  setup_prometheus:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set up kubelogin for non-interactive login
        uses: azure/use-kubelogin@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          kubelogin-version: 'latest'

      - name: Kubectl tool installer
        uses: Azure/setup-kubectl@v4.0.0
        
      - name: Get AKS context
        uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ vars.RESOURCE_GROUP }}
          cluster-name: ${{ vars.CLUSTER_NAME }}
          use-kubelogin: 'true'

      - name: Helm tool installer
        uses: Azure/setup-helm@v4
        
      - name: Add Helm repository
        run: |
          helm -n kms upgrade --install --create-namespace kms ./ -f ./example-values/minikube.yaml
          helm repo update
