name: lint-helm

on:
  [push]

jobs:
  lint-helm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        paths:
          - "test-values/test-values1.yaml"
    steps:
      - uses: actions/checkout@v3

      - name: test with  ${{ matrix.paths }}
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: helm lint . -f ${{ matrix.paths }}