name: lint-helm-test-template

on:
  [push]

jobs:
  test-n-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        paths:
          - "test-values/test-values1.yaml"
    steps:
      - uses: actions/checkout@v3

      - name: test with  ${{ matrix.paths }}
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: helm lint . -f ${{ matrix.paths }}

      - uses: balchua/microk8s-actions@v0.3.0
        with:
          channel: '1.25/stable'
      - name: Test ${{ matrix.paths }}
        id: k8s
        run: |
          helm template kms . -f ${{ matrix.paths }} > output.yaml
          kubectl create ns kms
          kubectl apply -f output.yaml -n kms 
          sleep 90
          kubectl get pods -n kms -o=jsonpath='{.items[*].status.containerStatuses}'  | jq
          kubectl rollout status deployment kms-kms-generic-helm-charts -n kms
          kubectl get pods -n kms -o=jsonpath='{.items[*].status.containerStatuses}'  | jq
          running=`kubectl get pods -n kms -o=jsonpath='{range .items[*]}{.metadata.name}{"="}{.status.containerStatuses[0].started}{"\n"}'` 
          
          if [[ "$running" == *"false"* ]]; then
            echo "It's there."
            echo running=false >> "$GITHUB_OUTPUT"
          fi

      - name: test if we failed
        if: ${{ steps.k8s.outputs.running == 'false' }}
        run: exit 1

