name: lint-helm-test-template

on:
  [push]

jobs:
  lint-helm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        paths:
          - "test-values/test-values1.yaml"
    steps:
      - uses: actions/checkout@v3

      - name: test with  ${{ matrix.paths }}
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: helm lint . -f ${{ matrix.paths }}

      - uses: balchua/microk8s-actions@v0.3.0
        with:
          channel: '1.25/stable'
      - name: Test ${{ matrix.paths }}
        id: k8s
        run: |
          helm template . -f ${{ matrix.paths }} > output.yaml
          kubectl apply -f output.yaml
          sleep 5 
          kubectl get pods -A -o wide

