name: lint-helm

on:
  [push]

jobs:

  lint-helm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        paths:
          - "test-values/test-values1.yaml"
    steps:
      - uses: actions/checkout@v3

      - name: debug
        run: echo '${{ matrix.paths) }}'