name: test-k8s-files

on:
  [push]

jobs:
  lookup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.filelist.outputs.file_names }}
    steps:
    - uses: actions/checkout@v2
    - name: Get all value files
      id: filelist
      uses: the-coding-turtle/ga-file-list@v0.1
      with:
        directory: "test-values"
        file_extension: "yaml"

  lint-helm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        files: ${{fromJson(needs.lookup.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v3
      - name: Lint Helm
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: helm lint . -f ${{ matrix.TENANT }}"