name: lint-helm

on:
  [push]

jobs:
  lookup:
    runs-on: ubuntu-latest
    outputs:
      paths: ${{ steps.filelist.outputs.paths }}
    steps:
      - uses: actions/checkout@v2
      - name: list files
        id: filelist
        uses: Rishabh510/Path-lister-action@master
        with:
          path: "test-values/"
          type: ".yaml"

  lint-helm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        files: ${{ needs.filelist.outputs.paths }}
    steps:
      - uses: actions/checkout@v3
      - name: Output results
        run: |
          echo "Found ${{ matrix.files }}"