name: lint-helm

on:
  [push]

jobs:
  lookup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.filelist.outputs.file_names }}
    steps:
      - uses: actions/checkout@v2
      - name: list files
        id: lookup
        uses: Rishabh510/Path-lister-action@master
        with:
          path: "test-values/"
          type: ".yaml"

  lint-helm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        files: ${{ needs.lookup.outputs.file_names }}
    steps:
      - uses: actions/checkout@v3
      - name: Output results
        run: |
          echo "Found ${{ steps.filelist.outputs.file_names }} file(s) with this extension:"
          for i in ${{ steps.filelist.outputs.file_names }}; do
          echo $i
          done